name: CI/CD Pipeline

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker:
    if: github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mariasan8789 }}
          password: ${{ secrets.epin123E }}

      - name: Build and push Docker image
        run: |
          docker build -t mariasan8789/pzatask7:latest .
          docker push mariasan8789/pzatask7:latest
